- hosts: localhost
  become: true

  vars:
    # jenkins_repo_url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    # jenkins_repo_key_url: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
    jenkins_pkg_url: https://pkg.jenkins.io/redhat-stable
    jenkins_version: "2.289.2"
    jenkins_plugins: ['ansible', 'build-name-setter', 'build-timeout', 'configuration-as-code',  'docker-plugin', 'docker-workflow', 
    'google-kubernetes-engine', 'greenballs', 'kubernetes', 'monitoring', 'pipeline-maven', 'rebuild', 'schedule-build',  'ssh-slaves', 
    'timestamper', 'workflow-aggregator', 'blueocean',  'ws-cleanup'] 
    # Additional plugins
    # 'tfs', 'uno-choice', 'artifactory', 'emailext-template', 'environment-script']
    java_packages:
      - java-11-openjdk
    jenkins_prefer_lts: true
  
  roles:
    - ansible-role-jenkins

  post_tasks:
    - name: Check installed version of Jenkins.
      command: rpm -q jenkins
      args:
        warn: false
      changed_when: false
      register: jenkins_rpm_version
      tags: ['skip_ansible_lint']

    - name: Print installed Jenkins package information.
      debug: var=jenkins_rpm_version

    - name: Fail if version doesn't match what we wanted.
      fail:
      when: "jenkins_version not in jenkins_rpm_version.stdout"