- name: 'Copy Jenkins casc config file'
  copy:
    src: jenkins.yml
    dest: '{{ casc_jenkins_config_dir }}'
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_user }}"
    mode: 0600

- debug: msg="{{ lookup('env','CASC_JENKINS_CONFIG') }} is an environment variable"